# path to zend project root
repository_root: "./"
# release version to be backported (format "major.minor.patch", suffix must not be included if beta or candidate or alpha)
version: "5.0.4"
# build number (0-24 for beta (1-25), 25-49 for candidate (1-25), 50 for official, 51+ for alpha (1+))
build_number: "50"
# script steps flow
script_steps:
  # initialize_check_main_checked_out (sub)step
  initialize_check_main_checked_out:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # initialize_check_no_pending_changes (sub)step
  initialize_check_no_pending_changes:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # initialize_create_branch (sub)step
  initialize_create_branch:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # initialize_merge_branch (sub)step
  initialize_merge_branch:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # reset_client_version step
  reset_client_version:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # reset_checkpoints step
  reset_checkpoints:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # reset_changelog step
  reset_changelog:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # build_zend step
  build_zend:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # reset_man_pages step
  reset_man_pages:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
  # reset_release_notes step
  reset_release_notes:
    # skip step
    skip: False
    # stop before step (user interaction for proceeding)
    stop: False
