language: shell

os: linux

.com.github.horizenofficial.zen.env-definitions:
  - &docker_amd64_linux_ubuntu_bionic
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_bionic
      - DOCKER_IS_DEB=true
  - &docker_amd64_linux_ubuntu_bionic_legacy_cpu
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_bionic
      - DOCKER_IS_DEB=true
      - MAKEFLAGS="--legacy-cpu"
  - &docker_amd64_linux_ubuntu_jammy
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_jammy
      - DOCKER_IS_DEB=true
      - MAKEFLAGS="--enable-lcov"
  - &docker_amd64_linux_ubuntu_jammy_legacy_cpu
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_jammy
      - DOCKER_IS_DEB=true
      - MAKEFLAGS="--legacy-cpu"
  - &docker_amd64_windows_ubuntu_bionic
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=windows
      - DOCKER_FROM=ubuntu_bionic
      - DOCKER_IS_DEB=true
  - &docker_amd64_windows_ubuntu_bionic_legacy_cpu
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=windows
      - DOCKER_FROM=ubuntu_bionic
      - DOCKER_IS_DEB=true
      - MAKEFLAGS="--legacy-cpu"
  - &docker_amd64_linux_ubuntu_focal
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_focal
      - DOCKER_IS_DEB=true
  - &docker_amd64_linux_ubuntu_bionic_unit-tests
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_bionic
      - DOCKER_IS_DEB=true
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="btest gtest sec-hard no-dot-so util-test secp256k1 libsnark univalue"
  - &docker_amd64_linux_ubuntu_bionic_rpc-tests_1
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_bionic
      - DOCKER_IS_DEB=true
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-split=4:1"
  - &docker_amd64_linux_ubuntu_bionic_rpc-tests_2
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_bionic
      - DOCKER_IS_DEB=true
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-split=4:2"
  - &docker_amd64_linux_ubuntu_bionic_rpc-tests_3
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_bionic
      - DOCKER_IS_DEB=true
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-split=4:3"
  - &docker_amd64_linux_ubuntu_bionic_rpc-tests_4
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_bionic
      - DOCKER_IS_DEB=true
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-split=4:4"
  - &docker_amd64_linux_ubuntu_bionic_test-fetch-params
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_bionic
      - DOCKER_IS_DEB=true
      - TEST_CMD="./qa/zen/test-fetch-params.sh"
  - &docker_amd64_linux_ubuntu_jammy_unit-tests
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_jammy
      - DOCKER_IS_DEB=true
      - MAKEFLAGS="--enable-lcov"
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="btest gtest sec-hard no-dot-so util-test secp256k1 libsnark univalue --coverage"
  - &docker_amd64_linux_ubuntu_jammy_rpc-tests_1
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_jammy
      - DOCKER_IS_DEB=true
      - MAKEFLAGS="--enable-lcov"
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-split=4:1 --coverage"
  - &docker_amd64_linux_ubuntu_jammy_rpc-tests_2
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_jammy
      - DOCKER_IS_DEB=true
      - MAKEFLAGS="--enable-lcov"
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-split=4:2 --coverage"
  - &docker_amd64_linux_ubuntu_jammy_rpc-tests_3
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_jammy
      - DOCKER_IS_DEB=true
      - MAKEFLAGS="--enable-lcov"
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-split=4:3 --coverage"
  - &docker_amd64_linux_ubuntu_jammy_rpc-tests_4
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_jammy
      - DOCKER_IS_DEB=true
      - MAKEFLAGS="--enable-lcov"
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-split=4:4 --coverage"
  - &docker_amd64_linux_ubuntu_jammy_test-fetch-params
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_jammy
      - DOCKER_IS_DEB=true
      - MAKEFLAGS="--enable-lcov"
      - TEST_CMD="./qa/zen/test-fetch-params.sh"
  - &docker_amd64_linux_ubuntu_focal_unit-tests
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_focal
      - DOCKER_IS_DEB=true
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="btest gtest sec-hard no-dot-so util-test secp256k1 libsnark univalue"
  - &docker_amd64_linux_ubuntu_focal_rpc-tests_1
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_focal
      - DOCKER_IS_DEB=true
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-split=4:1"
  - &docker_amd64_linux_ubuntu_focal_rpc-tests_2
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_focal
      - DOCKER_IS_DEB=true
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-split=4:2"
  - &docker_amd64_linux_ubuntu_focal_rpc-tests_3
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_focal
      - DOCKER_IS_DEB=true
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-split=4:3"
  - &docker_amd64_linux_ubuntu_focal_rpc-tests_4
    env:
      - DOCKER_ARCH=amd64
      - DOCKER_TARGET_OS=linux
      - DOCKER_FROM=ubuntu_focal
      - DOCKER_IS_DEB=true
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-split=4:4"
  - &amd64_osx_xcode9_4_unit-tests
    env:
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="btest gtest util-test secp256k1 libsnark univalue"
      - MAKEFLAGS="--disable-libs --legacy-cpu"
  # TODO figure out why the excluded tests are failing on MacOS in Travis when we migrate to OSX 10.14 after 10.13 EOL
  - &amd64_osx_xcode9_4_rpc-tests_1
    env:
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-exclude=rpcbind_test.py,invalidblockrequest.py,invalidblockposthalving.py,p2p-acceptblock.py,wallet_mergetoaddress_2.py --rpc-split=10:1 --rpc-macrebalance"
      - MAKEFLAGS="--disable-libs --legacy-cpu"
  - &amd64_osx_xcode9_4_rpc-tests_2
    env:
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-exclude=rpcbind_test.py,invalidblockrequest.py,invalidblockposthalving.py,p2p-acceptblock.py,wallet_mergetoaddress_2.py --rpc-split=10:2 --rpc-macrebalance"
      - MAKEFLAGS="--disable-libs --legacy-cpu"
  - &amd64_osx_xcode9_4_rpc-tests_3
    env:
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-exclude=rpcbind_test.py,invalidblockrequest.py,invalidblockposthalving.py,p2p-acceptblock.py,wallet_mergetoaddress_2.py --rpc-split=10:3 --rpc-macrebalance"
      - MAKEFLAGS="--disable-libs --legacy-cpu"
  - &amd64_osx_xcode9_4_rpc-tests_4
    env:
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-exclude=rpcbind_test.py,invalidblockrequest.py,invalidblockposthalving.py,p2p-acceptblock.py,wallet_mergetoaddress_2.py --rpc-split=10:4 --rpc-macrebalance"
      - MAKEFLAGS="--disable-libs --legacy-cpu"
  - &amd64_osx_xcode9_4_rpc-tests_5
    env:
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-exclude=rpcbind_test.py,invalidblockrequest.py,invalidblockposthalving.py,p2p-acceptblock.py,wallet_mergetoaddress_2.py --rpc-split=10:5 --rpc-macrebalance"
      - MAKEFLAGS="--disable-libs --legacy-cpu"
  - &amd64_osx_xcode9_4_rpc-tests_6
    env:
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-exclude=rpcbind_test.py,invalidblockrequest.py,invalidblockposthalving.py,p2p-acceptblock.py,wallet_mergetoaddress_2.py --rpc-split=10:6 --rpc-macrebalance"
      - MAKEFLAGS="--disable-libs --legacy-cpu"
  - &amd64_osx_xcode9_4_rpc-tests_7
    env:
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-exclude=rpcbind_test.py,invalidblockrequest.py,invalidblockposthalving.py,p2p-acceptblock.py,wallet_mergetoaddress_2.py --rpc-split=10:7 --rpc-macrebalance"
      - MAKEFLAGS="--disable-libs --legacy-cpu"
  - &amd64_osx_xcode9_4_rpc-tests_8
    env:
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-exclude=rpcbind_test.py,invalidblockrequest.py,invalidblockposthalving.py,p2p-acceptblock.py,wallet_mergetoaddress_2.py --rpc-split=10:8 --rpc-macrebalance"
      - MAKEFLAGS="--disable-libs --legacy-cpu"
  - &amd64_osx_xcode9_4_rpc-tests_9
    env:
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-exclude=rpcbind_test.py,invalidblockrequest.py,invalidblockposthalving.py,p2p-acceptblock.py,wallet_mergetoaddress_2.py --rpc-split=10:9 --rpc-macrebalance"
      - MAKEFLAGS="--disable-libs --legacy-cpu"
  - &amd64_osx_xcode9_4_rpc-tests_10
    env:
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-extended --rpc-exclude=rpcbind_test.py,invalidblockrequest.py,invalidblockposthalving.py,p2p-acceptblock.py,wallet_mergetoaddress_2.py --rpc-split=10:10 --rpc-macrebalance"
      - MAKEFLAGS="--disable-libs --legacy-cpu"
  - &amd64_osx_xcode9_4_rpc-tests_11
    env:
      - TEST_CMD="./qa/zcash/full_test_suite.py"
      - TEST_ARGS="rpc --rpc-runonly=wallet_mergetoaddress_2.py"
      - MAKEFLAGS="--disable-libs --legacy-cpu"

.com.github.horizenofficial.zen.job-definitions:
  - &prepare_docker_amd64
    os: linux
    dist: focal
    cache: false
    script:
      - bash "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/prepare/docker_image_build.sh"
      - bash "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/prepare/docker_image_deploy.sh"
  - &build_docker_amd64_x-large
    os: linux
    dist: focal
    vm:
      size: x-large
    cache:
      directories:
        - "$HOME/.ccache"
        - depends/built
        - depends/sources
        - depends/work
        - depends/x86_64*
    script:
      - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/build/build_${TRAVIS_CPU_ARCH}_${DOCKER_TARGET_OS}_${DOCKER_FROM}.sh"
      - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/push_archive.sh ${B2_UL_COMPRESS_FOLDER} ${B2_UL_FILENAME}"
  - &test_docker_amd64
    if: NOT env(SKIP_TESTS)
    os: linux
    dist: focal
    cache:
      directories:
        - "$HOME/.zcash-params"
    script:
      - bash -c "RENAME_FOLDER='true' RENAME_SUFFIX='_clean' ${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/get_archive.sh ${B2_DL_DECOMPRESS_FOLDER} ${B2_DL_FILENAME}"
      - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/travis_stay_alive.sh"
      - bash -c '${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/test/run_test.sh "${TEST_CMD}" "${TEST_ARGS}"'
  - &test_docker_amd64_x-large
    if: NOT env(SKIP_TESTS)
    os: linux
    dist: focal
    vm:
      size: x-large
    cache:
      directories:
        - "$HOME/.zcash-params"
    script:
      - bash -c "RENAME_FOLDER='true' RENAME_SUFFIX='_clean' ${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/get_archive.sh ${B2_DL_DECOMPRESS_FOLDER} ${B2_DL_FILENAME}"
      - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/travis_stay_alive.sh"
      - bash -c '${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/test/run_test.sh "${TEST_CMD}" "${TEST_ARGS}"'
  - &test_osx_xcode9_4
    if: NOT env(SKIP_TESTS) AND NOT env(SKIP_OSX) OR tag IS present # Never skip MacOS when running the CI for a tag
    os: osx
    osx_image: xcode9.4
    cache:
      directories:
        - "$HOME/ZcashParams"
    script:
      - bash -c "RENAME_FOLDER='true' RENAME_SUFFIX='_clean' ${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/get_archive.sh ${B2_DL_DECOMPRESS_FOLDER} ${B2_DL_FILENAME}"
      - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/travis_stay_alive.sh"
      - bash -c '${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/test/run_test.sh "${TEST_CMD}" "${TEST_ARGS}"'
  - &finalize_docker_amd64_x-large
    os: linux
    dist: focal
    vm:
      size: x-large
    script:
      - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/test/finalize_${TRAVIS_CPU_ARCH}_${DOCKER_TARGET_OS}_${DOCKER_FROM}.sh"

before_install:
  - source "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/setup_environment.sh"

install:
  - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/install.sh"

jobs:
  include:
    # build and push docker build/test dependency images
    - stage: Prepare
      <<: *prepare_docker_amd64
      <<: *docker_amd64_linux_ubuntu_bionic
    - stage: Prepare
      <<: *prepare_docker_amd64
      <<: *docker_amd64_linux_ubuntu_jammy
    - stage: Prepare
      <<: *prepare_docker_amd64
      <<: *docker_amd64_linux_ubuntu_focal
    - stage: Prepare
      <<: *prepare_docker_amd64
      <<: *docker_amd64_windows_ubuntu_bionic

    # build zencash-apple toolchain
    - stage: Prepare
      if: NOT env(SKIP_OSX) OR tag IS present
      os: osx
      osx_image: xcode9.4
      cache: false
      script:
        - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/prepare/build_zencash-apple.sh"
        - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/push_archive.sh ${B2_UL_COMPRESS_FOLDER} ${B2_UL_FILENAME}"

    # Docker based builds
    - stage: Build
      <<: *build_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_bionic
    - stage: Build
      <<: *build_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_bionic_legacy_cpu
    - stage: Build
      <<: *build_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_jammy
    - stage: Build
      <<: *build_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_jammy_legacy_cpu
    - stage: Build
      <<: *build_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_focal
    - stage: Build
      <<: *build_docker_amd64_x-large
      <<: *docker_amd64_windows_ubuntu_bionic
    - stage: Build
      <<: *build_docker_amd64_x-large
      <<: *docker_amd64_windows_ubuntu_bionic_legacy_cpu
    # osx build
    - stage: Build
      if: NOT env(SKIP_OSX) OR tag IS present
      os: osx
      osx_image: xcode9.4
      env:
        - MAKEFLAGS="--disable-libs --legacy-cpu"
      cache:
        directories:
          - "$HOME/.ccache"
          - depends/built
          - depends/sources
          - depends/work
          - depends/x86_64*
      script:
        - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/get_archive.sh ${B2_DL_DECOMPRESS_FOLDER} ${B2_DL_FILENAME}"
        - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/travis_stay_alive.sh"
        - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/build/build_${TRAVIS_CPU_ARCH}_${TRAVIS_OS_NAME}_${TRAVIS_OSX_IMAGE}.sh"
        - bash -c "${TRAVIS_BUILD_DIR}/contrib/ci-horizen/scripts/common/push_archive.sh ${B2_UL_COMPRESS_FOLDER} ${B2_UL_FILENAME}"
    # Docker based tests
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_bionic_unit-tests
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_bionic_rpc-tests_1
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_bionic_rpc-tests_2
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_bionic_rpc-tests_3
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_bionic_rpc-tests_4
    - stage: Test
      <<: *test_docker_amd64
      <<: *docker_amd64_linux_ubuntu_bionic_test-fetch-params
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_jammy_unit-tests
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_jammy_rpc-tests_1
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_jammy_rpc-tests_2
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_jammy_rpc-tests_3
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_jammy_rpc-tests_4
    - stage: Test
      <<: *test_docker_amd64
      <<: *docker_amd64_linux_ubuntu_jammy_test-fetch-params
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_focal_unit-tests
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_focal_rpc-tests_1
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_focal_rpc-tests_2
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_focal_rpc-tests_3
    - stage: Test
      <<: *test_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_focal_rpc-tests_4
    # osx based tests
    - stage: Test
      <<: *test_osx_xcode9_4
      <<: *amd64_osx_xcode9_4_unit-tests
    - stage: Test
      <<: *test_osx_xcode9_4
      <<: *amd64_osx_xcode9_4_rpc-tests_1
    - stage: Test
      <<: *test_osx_xcode9_4
      <<: *amd64_osx_xcode9_4_rpc-tests_2
    - stage: Test
      <<: *test_osx_xcode9_4
      <<: *amd64_osx_xcode9_4_rpc-tests_3
    - stage: Test
      <<: *test_osx_xcode9_4
      <<: *amd64_osx_xcode9_4_rpc-tests_4
    - stage: Test
      <<: *test_osx_xcode9_4
      <<: *amd64_osx_xcode9_4_rpc-tests_5
    - stage: Test
      <<: *test_osx_xcode9_4
      <<: *amd64_osx_xcode9_4_rpc-tests_6
    - stage: Test
      <<: *test_osx_xcode9_4
      <<: *amd64_osx_xcode9_4_rpc-tests_7
    - stage: Test
      <<: *test_osx_xcode9_4
      <<: *amd64_osx_xcode9_4_rpc-tests_8
    - stage: Test
      <<: *test_osx_xcode9_4
      <<: *amd64_osx_xcode9_4_rpc-tests_9
    - stage: Test
      <<: *test_osx_xcode9_4
      <<: *amd64_osx_xcode9_4_rpc-tests_10
    - stage: Test
      <<: *test_osx_xcode9_4
      <<: *amd64_osx_xcode9_4_rpc-tests_11
    - stage: Finalize_coverage
      <<: *finalize_docker_amd64_x-large
      <<: *docker_amd64_linux_ubuntu_jammy
